/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MyGradesRouteImport } from './routes/my-grades'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as MyAssignmentsRouteImport } from './routes/my-assignments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsStudentIdRouteImport } from './routes/students.$studentId'
import { Route as StudentProfileStudentIdRouteImport } from './routes/student-profile.$studentId'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGradesRoute = MyGradesRouteImport.update({
  id: '/my-grades',
  path: '/my-grades',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAssignmentsRoute = MyAssignmentsRouteImport.update({
  id: '/my-assignments',
  path: '/my-assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsStudentIdRoute = StudentsStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentProfileStudentIdRoute = StudentProfileStudentIdRouteImport.update({
  id: '/student-profile/$studentId',
  path: '/student-profile/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-grades': typeof MyGradesRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/student-profile/$studentId': typeof StudentProfileStudentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-grades': typeof MyGradesRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/student-profile/$studentId': typeof StudentProfileStudentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/my-assignments': typeof MyAssignmentsRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-grades': typeof MyGradesRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/students': typeof StudentsRouteWithChildren
  '/student-profile/$studentId': typeof StudentProfileStudentIdRoute
  '/students/$studentId': typeof StudentsStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/my-assignments'
    | '/my-courses'
    | '/my-grades'
    | '/progress'
    | '/signup'
    | '/students'
    | '/student-profile/$studentId'
    | '/students/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/my-assignments'
    | '/my-courses'
    | '/my-grades'
    | '/progress'
    | '/signup'
    | '/students'
    | '/student-profile/$studentId'
    | '/students/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assignments'
    | '/dashboard'
    | '/login'
    | '/my-assignments'
    | '/my-courses'
    | '/my-grades'
    | '/progress'
    | '/signup'
    | '/students'
    | '/student-profile/$studentId'
    | '/students/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MyAssignmentsRoute: typeof MyAssignmentsRoute
  MyCoursesRoute: typeof MyCoursesRoute
  MyGradesRoute: typeof MyGradesRoute
  ProgressRoute: typeof ProgressRoute
  SignupRoute: typeof SignupRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  StudentProfileStudentIdRoute: typeof StudentProfileStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-grades': {
      id: '/my-grades'
      path: '/my-grades'
      fullPath: '/my-grades'
      preLoaderRoute: typeof MyGradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-assignments': {
      id: '/my-assignments'
      path: '/my-assignments'
      fullPath: '/my-assignments'
      preLoaderRoute: typeof MyAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$studentId': {
      id: '/students/$studentId'
      path: '/$studentId'
      fullPath: '/students/$studentId'
      preLoaderRoute: typeof StudentsStudentIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/student-profile/$studentId': {
      id: '/student-profile/$studentId'
      path: '/student-profile/$studentId'
      fullPath: '/student-profile/$studentId'
      preLoaderRoute: typeof StudentProfileStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudentsRouteChildren {
  StudentsStudentIdRoute: typeof StudentsStudentIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsStudentIdRoute: StudentsStudentIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MyAssignmentsRoute: MyAssignmentsRoute,
  MyCoursesRoute: MyCoursesRoute,
  MyGradesRoute: MyGradesRoute,
  ProgressRoute: ProgressRoute,
  SignupRoute: SignupRoute,
  StudentsRoute: StudentsRouteWithChildren,
  StudentProfileStudentIdRoute: StudentProfileStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
